<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app_identity_service.proto

namespace Google\AppEngine\Api\AppIdentity;

if (false) {
    /**
     * This class is deprecated. Use Google\AppEngine\Api\AppIdentity\AppIdentityServiceError\ErrorCode instead.
     * @deprecated
     */
    class AppIdentityServiceError_ErrorCode {}
}
class_exists(AppIdentityServiceError\ErrorCode::class);
@trigger_error('Google\AppEngine\Api\AppIdentity\AppIdentityServiceError_ErrorCode is deprecated and will be removed in the next major release. Use Google\AppEngine\Api\AppIdentity\AppIdentityServiceError\ErrorCode instead', E_USER_DEPRECATED);

