<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app_identity_service.proto

namespace Google\AppEngine\Api\AppIdentity;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>google.appEngine.api.appIdentity.GetAccessTokenResponse</code>
 */
class GetAccessTokenResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string access_token = 1;</code>
     */
    protected $access_token = null;
    /**
     * Seconds since the epoch.
     *
     * Generated from protobuf field <code>int64 expiration_time = 2;</code>
     */
    protected $expiration_time = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $access_token
     *     @type int|string $expiration_time
     *           Seconds since the epoch.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\AppIdentityService::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string access_token = 1;</code>
     * @return string
     */
    public function getAccessToken()
    {
        return isset($this->access_token) ? $this->access_token : '';
    }

    public function hasAccessToken()
    {
        return isset($this->access_token);
    }

    public function clearAccessToken()
    {
        unset($this->access_token);
    }

    /**
     * Generated from protobuf field <code>string access_token = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAccessToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->access_token = $var;

        return $this;
    }

    /**
     * Seconds since the epoch.
     *
     * Generated from protobuf field <code>int64 expiration_time = 2;</code>
     * @return int|string
     */
    public function getExpirationTime()
    {
        return isset($this->expiration_time) ? $this->expiration_time : 0;
    }

    public function hasExpirationTime()
    {
        return isset($this->expiration_time);
    }

    public function clearExpirationTime()
    {
        unset($this->expiration_time);
    }

    /**
     * Seconds since the epoch.
     *
     * Generated from protobuf field <code>int64 expiration_time = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setExpirationTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->expiration_time = $var;

        return $this;
    }

}

