<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app_identity_service.proto

namespace Google\AppEngine\Api\AppIdentity;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>google.appEngine.api.appIdentity.GetDefaultGcsBucketNameResponse</code>
 */
class GetDefaultGcsBucketNameResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * The default google storage bucket name for the application.
     *
     * Generated from protobuf field <code>string default_gcs_bucket_name = 1;</code>
     */
    protected $default_gcs_bucket_name = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $default_gcs_bucket_name
     *           The default google storage bucket name for the application.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\AppIdentityService::initOnce();
        parent::__construct($data);
    }

    /**
     * The default google storage bucket name for the application.
     *
     * Generated from protobuf field <code>string default_gcs_bucket_name = 1;</code>
     * @return string
     */
    public function getDefaultGcsBucketName()
    {
        return isset($this->default_gcs_bucket_name) ? $this->default_gcs_bucket_name : '';
    }

    public function hasDefaultGcsBucketName()
    {
        return isset($this->default_gcs_bucket_name);
    }

    public function clearDefaultGcsBucketName()
    {
        unset($this->default_gcs_bucket_name);
    }

    /**
     * The default google storage bucket name for the application.
     *
     * Generated from protobuf field <code>string default_gcs_bucket_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setDefaultGcsBucketName($var)
    {
        GPBUtil::checkString($var, True);
        $this->default_gcs_bucket_name = $var;

        return $this;
    }

}

