<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app_identity_service.proto

namespace Google\AppEngine\Api\AppIdentity;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>google.appEngine.api.appIdentity.GetPublicCertificateForAppResponse</code>
 */
class GetPublicCertificateForAppResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .google.appEngine.api.appIdentity.PublicCertificate public_certificate_list = 1;</code>
     */
    private $public_certificate_list;
    /**
     * Generated from protobuf field <code>int64 max_client_cache_time_in_second = 2;</code>
     */
    protected $max_client_cache_time_in_second = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Google\AppEngine\Api\AppIdentity\PublicCertificate[]|\Google\Protobuf\Internal\RepeatedField $public_certificate_list
     *     @type int|string $max_client_cache_time_in_second
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\AppIdentityService::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .google.appEngine.api.appIdentity.PublicCertificate public_certificate_list = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPublicCertificateList()
    {
        return $this->public_certificate_list;
    }

    /**
     * Generated from protobuf field <code>repeated .google.appEngine.api.appIdentity.PublicCertificate public_certificate_list = 1;</code>
     * @param \Google\AppEngine\Api\AppIdentity\PublicCertificate[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPublicCertificateList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\AppEngine\Api\AppIdentity\PublicCertificate::class);
        $this->public_certificate_list = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 max_client_cache_time_in_second = 2;</code>
     * @return int|string
     */
    public function getMaxClientCacheTimeInSecond()
    {
        return isset($this->max_client_cache_time_in_second) ? $this->max_client_cache_time_in_second : 0;
    }

    public function hasMaxClientCacheTimeInSecond()
    {
        return isset($this->max_client_cache_time_in_second);
    }

    public function clearMaxClientCacheTimeInSecond()
    {
        unset($this->max_client_cache_time_in_second);
    }

    /**
     * Generated from protobuf field <code>int64 max_client_cache_time_in_second = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMaxClientCacheTimeInSecond($var)
    {
        GPBUtil::checkInt64($var);
        $this->max_client_cache_time_in_second = $var;

        return $this;
    }

}

