<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app_identity_service.proto

namespace Google\AppEngine\Api\AppIdentity;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>google.appEngine.api.appIdentity.GetServiceAccountNameResponse</code>
 */
class GetServiceAccountNameResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string service_account_name = 1;</code>
     */
    protected $service_account_name = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $service_account_name
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\AppIdentityService::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string service_account_name = 1;</code>
     * @return string
     */
    public function getServiceAccountName()
    {
        return isset($this->service_account_name) ? $this->service_account_name : '';
    }

    public function hasServiceAccountName()
    {
        return isset($this->service_account_name);
    }

    public function clearServiceAccountName()
    {
        unset($this->service_account_name);
    }

    /**
     * Generated from protobuf field <code>string service_account_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setServiceAccountName($var)
    {
        GPBUtil::checkString($var, True);
        $this->service_account_name = $var;

        return $this;
    }

}

