<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app_identity_service.proto

namespace Google\AppEngine\Api\AppIdentity;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>google.appEngine.api.appIdentity.SignForAppRequest</code>
 */
class SignForAppRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * optional string app_id = 2;
     *
     * Generated from protobuf field <code>bytes bytes_to_sign = 1;</code>
     */
    protected $bytes_to_sign = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $bytes_to_sign
     *           optional string app_id = 2;
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\AppIdentityService::initOnce();
        parent::__construct($data);
    }

    /**
     * optional string app_id = 2;
     *
     * Generated from protobuf field <code>bytes bytes_to_sign = 1;</code>
     * @return string
     */
    public function getBytesToSign()
    {
        return isset($this->bytes_to_sign) ? $this->bytes_to_sign : '';
    }

    public function hasBytesToSign()
    {
        return isset($this->bytes_to_sign);
    }

    public function clearBytesToSign()
    {
        unset($this->bytes_to_sign);
    }

    /**
     * optional string app_id = 2;
     *
     * Generated from protobuf field <code>bytes bytes_to_sign = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setBytesToSign($var)
    {
        GPBUtil::checkString($var, False);
        $this->bytes_to_sign = $var;

        return $this;
    }

}

