<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app_identity_service.proto

namespace Google\AppEngine\Api\AppIdentity;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>google.appEngine.api.appIdentity.SignForAppResponse</code>
 */
class SignForAppResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string key_name = 1;</code>
     */
    protected $key_name = null;
    /**
     * Generated from protobuf field <code>bytes signature_bytes = 2;</code>
     */
    protected $signature_bytes = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $key_name
     *     @type string $signature_bytes
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\AppIdentityService::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string key_name = 1;</code>
     * @return string
     */
    public function getKeyName()
    {
        return isset($this->key_name) ? $this->key_name : '';
    }

    public function hasKeyName()
    {
        return isset($this->key_name);
    }

    public function clearKeyName()
    {
        unset($this->key_name);
    }

    /**
     * Generated from protobuf field <code>string key_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setKeyName($var)
    {
        GPBUtil::checkString($var, True);
        $this->key_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes signature_bytes = 2;</code>
     * @return string
     */
    public function getSignatureBytes()
    {
        return isset($this->signature_bytes) ? $this->signature_bytes : '';
    }

    public function hasSignatureBytes()
    {
        return isset($this->signature_bytes);
    }

    public function clearSignatureBytes()
    {
        unset($this->signature_bytes);
    }

    /**
     * Generated from protobuf field <code>bytes signature_bytes = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSignatureBytes($var)
    {
        GPBUtil::checkString($var, False);
        $this->signature_bytes = $var;

        return $this;
    }

}

